=== jkoppel/project-ironfist/src/xsd/artifacts_xml.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="artifacts">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="artifact" type="artifact_t" maxOccurs="unbounded" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="artifact_t">
        <xs:choice minOccurs="0" maxOccurs="unbounded">
            <xs:element name="title" type="xs:string" />
            <xs:element name="description" type="xs:string" />
            <xs:element name="event" type="xs:string" />
        </xs:choice>
        <xs:attribute name="id" type="xs:int" use="required" />
        <xs:attribute name="name" type="xs:string" use="required" />
        <xs:attribute name="level" type="level_t" use="required" />
        <xs:attribute name="cursed" type="xs:boolean" use="optional" />
        <xs:attribute name="campaign_only" type="xs:boolean" use="optional" />
    </xs:complexType>

    <xs:simpleType name="level_t">
        <xs:restriction base="xs:string">
            <xs:enumeration value="ultimate" />
            <xs:enumeration value="major" />
            <xs:enumeration value="minor" />
            <xs:enumeration value="treasure" />
            <xs:enumeration value="spellbook" />
            <xs:enumeration value="unused" />
        </xs:restriction>
    </xs:simpleType>

</xs:schema>

=== jkoppel/project-ironfist/data/artifacts.xml
<?xml version="1.0"?>
<artifacts xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:noNamespaceSchemaLocation="artifacts_xml.xsd">
    <artifact id="0" name="Ultimate Book of Knowledge" level="ultimate">
        <title>Ultimate Book&#10;(+12 Knowledge)</title>
        <description>The Ultimate Book of Knowledge increases your knowledge by 12.</description>
    </artifact>
    <artifact id="1" name="Ultimate Sword of Dominion" level="ultimate">
        <title>Ultimate Sword&#10;(+12 Attack)</title>
        <description>The Ultimate Sword of Dominion increases your attack skill by 12.</description>
    </artifact>
    <artifact id="2" name="Ultimate Cloak of Protection" level="ultimate">
        <title>Ultimate Cloak&#10;(+12 Defense)</title>
        <description>The Ultimate Cloak of Protection increases your defense skill by 12.</description>
    </artifact>
    <artifact id="3" name="Ultimate Wand of Magic" level="ultimate">
        <title>Ultimate Wand&#10;(+12 Spell Power)</title>
        <description>The Ultimate Wand of Magic increases your spell power by 12.</description>
    </artifact>
    <artifact id="4" name="Ultimate Shield" level="ultimate">
        <title>Ultimate Shield</title>
        <description>The Ultimate Shield increases your attack and defense skills by 6 each.</description>
    </artifact>
    <artifact id="5" name="Ultimate Staff" level="ultimate">
        <title>Ultimate Staff</title>
        <description>The Ultimate Staff increases your spell power and knowledge by 6 each.</description>
    </artifact>
    <artifact id="6" name="Ultimate Crown" level="ultimate">
        <title>Ultimate Crown</title>
        <description>The Ultimate Crown increases each of your basic skills by 4 points.</description>
    </artifact>
    <artifact id="7" name="Golden Goose" level="ultimate">
        <title>Golden Goose</title>
        <description>The Golden Goose brings in an income of 10,000 gold per turn.</description>
    </artifact>
    <artifact id="8" name="Arcane Necklace of Magic" level="major">
        <title>Arcane Necklace&#10;(+4 Spell Power)</title>
        <description>The Arcane Necklace of Magic increases your spell power by 4.</description>
        <event>After rescuing a Sorceress from a cursed tomb, she rewards your heroism with an exquisite jeweled necklace.</event>
    </artifact>
    <artifact id="9" name="Caster's Bracelet of Magic" level="minor">
        <title>Caster's Bracelet&#10;(+2 Spell Power)</title>
        <description>The Caster's Bracelet of Magic increases your spell power by 2.</description>
        <event>While searching through the rubble of a caved-in mine, you free a group of trapped Dwarves.  Grateful, the leader gives you a golden bracelet.</event>
    </artifact>
    <artifact id="10" name="Mage's Ring of Power" level="minor">
        <title>Mage's Ring&#10;(+2 Spell Power)</title>
        <description>The Mage's Ring of Power increases your spell power by 2.</description>
        <event>A cry of pain leads you to a Centaur, caught in a trap.  Upon setting the creature free, he hands you a small pouch.  Emptying the contents, you find a dazzling jeweled ring.</event>
    </artifact>
    <artifact id="11" name="Witch's Broach of Magic" level="major">
        <title>Witches Broach&#10;(+3 Spell Power)</title>
        <description>The Witch's Broach of Magic increases your spell power by 3.</description>
        <event>Alongside the remains of a burnt witch lies a beautiful broach, intricately designed.  Approaching the corpse with caution, you add the broach to your inventory.</event>
    </artifact>
    <artifact id="12" name="Medal of Valor" level="treasure">
        <title>Medal</title>
        <description>The Medal of Valor increases your morale.</description>
        <event>Freeing a virtuous maiden from the clutches of an evil overlord, you are granted a Medal of Valor by the King's herald.</event>
    </artifact>
    <artifact id="13" name="Medal of Courage" level="treasure">
        <title>Medal</title>
        <description>The Medal of Courage increases your morale.</description>
        <event>After saving a young boy from a vicious pack of Wolves, you return him to his father's manor.  The grateful nobleman awards you with a Medal of Courage.</event>
    </artifact>
    <artifact id="14" name="Medal of Honor" level="treasure">
        <title>Medal</title>
        <description>The Medal of Honor increases your morale.</description>
        <event>After freeing a princess of a neighboring kingdom from the evil clutches of despicable slavers, she awards you with a Medal of Honor.</event>
    </artifact>
    <artifact id="15" name="Medal of Distinction" level="treasure">
        <title>Medal</title>
        <description>The Medal of Distinction increases your morale.</description>
        <event>Ridding the countryside of the hideous Minotaur who made a sport of eating noblemen's Knights, you are honored with the Medal of Distinction.</event>
    </artifact>
    <artifact id="16" name="Fizbin of Misfortune" level="treasure" cursed="true">
        <title>Fizbin</title>
        <description>The Fizbin of Misfortune greatly decreases your morale.</description>
        <event>You stumble upon a medal lying alongside the empty road.  Adding the medal to your inventory, you become aware that you have acquired the undesirable Fizbin of Misfortune, greatly decreasing your army's morale.</event>
    </artifact>
    <artifact id="17" name="Thunder Mace of Dominion" level="treasure">
        <title>Thunder Mace&#10;(+1 Attack)</title>
        <description>The Thunder Mace of Dominion increases your attack skill by 1.</description>
        <event>During a sudden storm, a bolt of lightning strikes a tree, splitting it.  Inside the tree you find a mysterious mace.</event>
    </artifact>
    <artifact id="18" name="Armored Gauntlets of Protection" level="treasure">
        <title>Armored Gauntlets&#10;(+1 Defense)</title>
        <description>The Armored Gauntlets of Protection increase your defense skill by 1.</description>
        <event>You encounter the infamous Black Knight!  After a grueling duel ending in a draw, the Knight, out of respect, offers you a pair of armored gauntlets.</event>
    </artifact>
    <artifact id="19" name="Defender Helm of Protection" level="treasure">
        <title>Defender Helm&#10;(+1 Defense)</title>
        <description>The Defender Helm of Protection increases your defense skill by 1.</description>
        <event>A glint of golden light catches your eye.  Upon further investigation, you find a golden helm hidden under a bush.</event>
    </artifact>
    <artifact id="20" name="Giant Flail of Dominion" level="treasure">
        <title>Giant Flail&#10;(+1 Attack)</title>
        <description>The Giant Flail of Dominion increases your attack skill by 1.</description>
        <event>A clumsy Giant has killed himself with his own flail.  Knowing your superior skill with this weapon, you confidently remove the spectacular flail from the fallen Giant.</event>
    </artifact>
    <artifact id="21" name="Ballista of Quickness" level="major">
        <title>Ballista</title>
        <description>The Ballista of Quickness lets your catapult fire twice per combat round.</description>
        <event>Walking through the ruins of an ancient walled city, you find the instrument of the city's destruction, an elaborately crafted ballista.</event>
    </artifact>
    <artifact id="22" name="Stealth Shield of Protection" level="minor">
        <title>Stealth Shield&#10;(+2 Defense)</title>
        <description>The Stealth Shield of Protection increases your defense skill by 2.</description>
        <event>A stone statue of a warrior holds a silver shield.  As you remove the shield, the statue crumbles into dust.</event>
    </artifact>
    <artifact id="23" name="Dragon Sword of Dominion" level="major">
        <title>Dragon Sword&#10;(+3 Attack)</title>
        <description>The Dragon Sword of Dominion increases your attack skill by 3.</description>
        <event>As you are walking along a narrow path, a nearby bush suddenly bursts into flames.  Before your eyes the flames become the image of a beautiful woman.  She holds out a magnificent sword to you.</event>
    </artifact>
    <artifact id="24" name="Power Axe of Dominion" level="minor">
        <title>Power Axe&#10;(+2 Attack)</title>
        <description>The Power Axe of Dominion increases your attack skill by 2.</description>
        <event>You see a silver axe embedded deeply in the ground.  After several unsuccessful attempts by your army to remove the axe, you tightly grip the handle of the axe and effortlessly pull it free.</event>
    </artifact>
    <artifact id="25" name="Divine Breastplate of Protection" level="major">
        <title>Divine Breastplate&#10;(+3 Defense)</title>
        <description>The Divine Breastplate of Protection increases your defense skill by 3.</description>
        <event>A gang of Rogues is sifting through the possessions of dead warriors.  Scaring off the scavengers, you note the Rogues had overlooked a beautiful breastplate.</event>
    </artifact>
    <artifact id="26" name="Minor Scroll of Knowledge" level="minor">
        <title>Minor Scroll&#10;(+2 Knowledge)</title>
        <description>The Minor Scroll of Knowledge increases your knowledge by 2.</description>
        <event>Before you appears a levitating glass case with a scroll, perched upon a bed of crimson velvet.  At your touch, the lid opens and the scroll floats into your awaiting hands.</event>
    </artifact>
    <artifact id="27" name="Major Scroll of Knowledge" level="major">
        <title>Major Scroll&#10;(+3 Knowledge)</title>
        <description>The Major Scroll of Knowledge increases your knowledge by 3.</description>
