=== jkoppel/project-ironfist/ironfist/src/xsd/creatures_xml.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:complexType name="creatures_t">
    <xs:sequence>
      <xs:element ref="creature" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="damage_t">
    <xs:attribute name="minimum" type="xs:int" use="required"/>
    <xs:attribute name="maximum" type="xs:int" use="required"/>
  </xs:complexType>

  <xs:complexType name="random-spawn_t">
    <xs:attribute name="minimum" type="xs:int" use="required"/>
    <xs:attribute name="maximum" type="xs:int" use="required"/>
  </xs:complexType>

  <xs:complexType name="creature-attribute_t">
    <xs:attribute name="name" type="xs:string" use="required"/>
  </xs:complexType>
  
  <xs:complexType name="creature_t">
    <xs:choice maxOccurs="unbounded">
      <xs:element ref="damage" minOccurs="1" maxOccurs="1"/>
      <xs:element ref="random-spawn" minOccurs="1" maxOccurs="1"/>
      <xs:element ref="creature-attribute"/>
    </xs:choice>
    <xs:attribute name="id" type="xs:int" use="required"/>
    <xs:attribute name="name-singular" type="xs:string" use="required"/>
    <xs:attribute name="name-plural" type="xs:string" use="required"/>
    <xs:attribute name="icn" type="xs:string" use="required"/>
    <xs:attribute name="frm" type="xs:string" use="required"/>
    <xs:attribute name="cost" type="xs:int" use="required"/>
    <xs:attribute name="fight-value" type="xs:int" use="required"/>
    <xs:attribute name="fight-value-aux" type="xs:int" use="required"/>
    <xs:attribute name="growth" type="xs:int" use="required"/>
    <xs:attribute name="hp" type="xs:int" use="required"/>
    <xs:attribute name="faction" type="xs:int" use="required"/>
    <xs:attribute name="speed" type="xs:int" use="required"/>
    <xs:attribute name="attack" type="xs:int" use="required"/>
    <xs:attribute name="defense" type="xs:int" use="required"/>
    <xs:attribute name="shots" type="xs:int" use="required"/>
    <xs:attribute name="short-name" type="xs:string" use="required"/>
  </xs:complexType>

  <xs:element name="creatures" type="creatures_t"/>
  <xs:element name="creature" type="creature_t"/>
  <xs:element name="damage" type="damage_t"/>
  <xs:element name="random-spawn" type="random-spawn_t"/>
  <xs:element name="creature-attribute" type="creature-attribute_t"/>
  

</xs:schema>

=== jkoppel/project-ironfist/data/creatures.xml
<?xml version="1.0"?>
<creatures xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:noNamespaceSchemaLocation="creatures_xml.xsd">
    <creature id="0" name-singular="peasant" name-plural="peasants" icn="peasant.icn" frm="peas_frm.bin" projectile="" cost="20" fight-value="33" fight-value-aux="17" growth="12" hp="1" faction="0" speed="2" attack="1" defense="1" shots="0" short-name="psnt">
        <damage minimum="1" maximum="1"/>
        <random-spawn minimum="40" maximum="80"/>
    </creature>
    <creature id="1" name-singular="archer" name-plural="archers" icn="archer.icn" frm="archrfrm.bin" projectile="arch_msl.icn" cost="150" fight-value="312" fight-value-aux="21" growth="8" hp="10" faction="0" speed="2" attack="5" defense="3" shots="12" short-name="arch">
        <damage minimum="2" maximum="3"/>
        <creature-attribute name="shoots"/>
        <random-spawn minimum="20" maximum="30"/>
    </creature>
    <creature id="2" name-singular="ranger" name-plural="rangers" icn="archer2.icn" frm="archrfrm.bin" projectile="arch_msl.icn" cost="200" fight-value="463" fight-value-aux="23" growth="8" hp="10" faction="0" speed="4" attack="5" defense="3" shots="24" short-name="arch">
        <damage minimum="2" maximum="3"/>
        <creature-attribute name="shoots"/>
        <random-spawn minimum="20" maximum="30"/>
    </creature>
    <creature id="3" name-singular="pikeman" name-plural="pikemen" icn="pikeman.icn" frm="pikmnfrm.bin" projectile="" cost="200" fight-value="639" fight-value-aux="32" growth="5" hp="15" faction="0" speed="4" attack="5" defense="9" shots="0" short-name="pike">
        <damage minimum="3" maximum="4"/>
        <random-spawn minimum="20" maximum="30"/>
    </creature>
    <creature id="4" name-singular="veteran pikeman" name-plural="veteran pikemen" icn="pikeman2.icn" frm="pikmnfrm.bin" projectile="" cost="250" fight-value="824" fight-value-aux="33" growth="5" hp="20" faction="0" speed="5" attack="5" defense="9" shots="0" short-name="pike">
        <damage minimum="3" maximum="4"/>
        <random-spawn minimum="20" maximum="30"/>
    </creature>
    <creature id="5" name-singular="swordsman" name-plural="swordsmen" icn="swordsmn.icn" frm="swrdsfrm.bin" projectile="" cost="250" fight-value="1130" fight-value-aux="45" growth="4" hp="25" faction="0" speed="4" attack="7" defense="9" shots="0" short-name="swdm">
        <damage minimum="4" maximum="6"/>
        <random-spawn minimum="12" maximum="25"/>
    </creature>
    <creature id="6" name-singular="master swordsman" name-plural="master swordsmen" icn="swordsm2.icn" frm="swrdsfrm.bin" projectile="" cost="300" fight-value="1350" fight-value-aux="45" growth="4" hp="30" faction="0" speed="5" attack="7" defense="9" shots="0" short-name="swdm">
        <damage minimum="4" maximum="6"/>
        <random-spawn minimum="12" maximum="25"/>
    </creature>
    <creature id="7" name-singular="cavalry" name-plural="cavalries" icn="cavalryr.icn" frm="cvlryfrm.bin" projectile="" cost="300" fight-value="1830" fight-value-aux="61" growth="3" hp="30" faction="0" speed="6" attack="10" defense="9" shots="0" short-name="cavl">
        <damage minimum="5" maximum="10"/>
        <creature-attribute name="two-hex"/>
        <random-spawn minimum="10" maximum="18"/>
    </creature>
    <creature id="8" name-singular="champion" name-plural="champions" icn="cavalryb.icn" frm="cvlr2frm.bin" projectile="" cost="375" fight-value="2273" fight-value-aux="61" growth="3" hp="40" faction="0" speed="7" attack="10" defense="9" shots="0" short-name="cavl">
        <damage minimum="5" maximum="10"/>
        <creature-attribute name="two-hex"/>
        <random-spawn minimum="8" maximum="16"/>
    </creature>
    <creature id="9" name-singular="paladin" name-plural="paladins" icn="paladin.icn" frm="paladfrm.bin" projectile="" cost="600" fight-value="4704" fight-value-aux="78" growth="2" hp="50" faction="0" speed="5" attack="11" defense="12" shots="0" short-name="pldn">
        <damage minimum="10" maximum="20"/>
        <random-spawn minimum="6" maximum="12"/>
    </creature>
    <creature id="10" name-singular="crusader" name-plural="crusaders" icn="paladin2.icn" frm="paladfrm.bin" projectile="" cost="1000" fight-value="5822" fight-value-aux="58" growth="2" hp="65" faction="0" speed="6" attack="11" defense="12" shots="0" short-name="pldn">
        <damage minimum="10" maximum="20"/>
        <random-spawn minimum="6" maximum="10"/>
    </creature>
    <creature id="11" name-singular="goblin" name-plural="goblins" icn="goblin.icn" frm="goblnfrm.bin" projectile="" cost="40" fight-value="109" fight-value-aux="27" growth="10" hp="3" faction="1" speed="4" attack="3" defense="1" shots="0" short-name="gbln">
        <damage minimum="1" maximum="2"/>
        <random-spawn minimum="25" maximum="40"/>
    </creature>
    <creature id="12" name-singular="orc" name-plural="orcs" icn="orc.icn" frm="orc__frm.bin" projectile="orc__msl.icn" cost="140" fight-value="299" fight-value-aux="21" growth="8" hp="10" faction="1" speed="2" attack="3" defense="4" shots="8" short-name="elf_">
        <damage minimum="2" maximum="3"/>
        <creature-attribute name="shoots"/>
        <random-spawn minimum="15" maximum="30"/>
    </creature>
    <creature id="13" name-singular="orc chief" name-plural="orc chiefs" icn="orc2.icn" frm="orc__frm.bin" projectile="orc__msl.icn" cost="175" fight-value="512" fight-value-aux="29" growth="8" hp="15" faction="1" speed="3" attack="3" defense="4" shots="16" short-name="elf_">
        <damage minimum="3" maximum="4"/>
        <creature-attribute name="shoots"/>
        <random-spawn minimum="15" maximum="30"/>
    </creature>
    <creature id="14" name-singular="wolf" name-plural="wolves" icn="wolf.icn" frm="wolf_frm.bin" projectile="" cost="200" fight-value="865" fight-value-aux="43" growth="5" hp="20" faction="1" speed="6" attack="6" defense="2" shots="0" short-name="wolf">
        <damage minimum="3" maximum="5"/>
        <creature-attribute name="two-hex"/>
        <random-spawn minimum="20" maximum="35"/>
    </creature>
    <creature id="15" name-singular="ogre" name-plural="ogres" icn="ogre.icn" frm="ogre_frm.bin" projectile="" cost="300" fight-value="1065" fight-value-aux="36" growth="4" hp="40" faction="1" speed="2" attack="9" defense="5" shots="0" short-name="ogre">
        <damage minimum="4" maximum="6"/>
        <random-spawn minimum="12" maximum="25"/>
    </creature>
    <creature id="16" name-singular="ogre lord" name-plural="ogre lords" icn="ogre2.icn" frm="ogre_frm.bin" projectile="" cost="500" fight-value="2070" fight-value-aux="41" growth="4" hp="60" faction="1" speed="4" attack="9" defense="5" shots="0" short-name="ogre">
        <damage minimum="5" maximum="7"/>
        <random-spawn minimum="10" maximum="20"/>
    </creature>
    <creature id="17" name-singular="troll" name-plural="trolls" icn="troll.icn" frm="trollfrm.bin" projectile="trollmsl.icn" cost="600" fight-value="1921" fight-value-aux="32" growth="3" hp="40" faction="1" speed="4" attack="10" defense="5" shots="8" short-name="trll">
        <damage minimum="5" maximum="7"/>
        <creature-attribute name="shoots"/>
        <random-spawn minimum="7" maximum="10"/>
    </creature>
    <creature id="18" name-singular="war troll" name-plural="war trolls" icn="troll2.icn" frm="trollfrm.bin" projectile="trollmsl.icn" cost="700" fight-value="2337" fight-value-aux="33" growth="3" hp="40" faction="1" speed="5" attack="10" defense="5" shots="16" short-name="trll">
        <damage minimum="7" maximum="9"/>
        <creature-attribute name="shoots"/>
        <random-spawn minimum="7" maximum="10"/>
    </creature>
    <creature id="19" name-singular="cyclops" name-plural="cyclopes" icn="cyclops.icn" frm="cyclofrm.bin" projectile="" cost="750" fight-value="6074" fight-value-aux="58" growth="2" hp="80" faction="1" speed="5" attack="12" defense="9" shots="0" short-name="cycl">
        <damage minimum="12" maximum="24"/>
        <creature-attribute name="two-hex-attack"/>
        <random-spawn minimum="5" maximum="7"/>
        <secondary-cost resource="crystal" cost="1"/>
    </creature>
    <creature id="20" name-singular="sprite" name-plural="sprites" icn="sprite.icn" frm="spritfrm.bin" projectile="" cost="50" fight-value="129" fight-value-aux="26" growth="8" hp="2" faction="2" speed="4" attack="4" defense="2" shots="0" short-name="sprt">
        <damage minimum="1" maximum="2"/>
        <creature-attribute name="flies"/>
        <random-spawn minimum="25" maximum="45"/>
    </creature>
    <creature id="21" name-singular="dwarf" name-plural="dwarves" icn="dwarf.icn" frm="dwarffrm.bin" projectile="" cost="200" fight-value="500" fight-value-aux="25" growth="6" hp="20" faction="2" speed="2" attack="6" defense="5" shots="0" short-name="dwrf">
        <damage minimum="2" maximum="4"/>
        <random-spawn minimum="12" maximum="25"/>
    </creature>
    <creature id="22" name-singular="battle dwarf" name-plural="battle dwarves" icn="dwarf2.icn" frm="dwarffrm.bin" projectile="" cost="250" fight-value="716" fight-value-aux="29" growth="6" hp="20" faction="2" speed="4" attack="6" defense="6" shots="0" short-name="dwrf">
        <damage minimum="2" maximum="4"/>
        <random-spawn minimum="10" maximum="22"/>
    </creature>
    <creature id="23" name-singular="elf" name-plural="elves" icn="elf.icn" frm="elf__frm.bin" projectile="elf__msl.icn" cost="250" fight-value="554" fight-value-aux="22" growth="4" hp="15" faction="2" speed="4" attack="4" defense="3" shots="24" short-name="elf_">
        <damage minimum="2" maximum="3"/>
        <creature-attribute name="shoots"/>
        <random-spawn minimum="15" maximum="30"/>
    </creature>
